const Sdata = {
    shopItems: [
      {
        id: 7,
        cover: "./images/shops/images.png",
        title: "Mapple Earphones",
        type: "PFE",
        universite : "Université De Tunis EL Manar",
        auteur: "alex rtfqt",
        prixLecture: 1.900,
        prixTelechargement: 2.800,

      },
      {
        id: 7,
        cover: "./images/shops/images.png",
        title: "Mapple Earphones",
        type: "PFE",
        universite : "Université De Tunis EL Manar",
        auteur: "alex rtfqt",
        prixLecture: 1.900,
        prixTelechargement: 2.800,
      },
      {
        id: 7,
        cover: "./images/shops/images.png",
        title: "Mapple Earphones",
        type: "PFE",
        universite : "Université De Tunis EL Manar",
        auteur: "alex rtfqt",
        prixLecture: 1.900,
        prixTelechargement: 2.800,
      },
      {
        id: 7,
        cover: "./images/shops/images.png",
        title: "Mapple Earphones",
        type: "PFE",
        universite : "Université De Tunis EL Manar",
        auteur: "alex rtfqt",
        prixLecture: 1.900,
        prixTelechargement: 2.800,
      },
      {
        id: 7,
        cover: "./images/shops/images.png",
        title: "Mapple Earphones",
        type: "PFE",
        universite : "Université De Tunis EL Manar",
        auteur: "alex rtfqt",
        prixLecture: 1.900,
        prixTelechargement: 2.800,
      },
      {
        id: 7,
        cover: "./images/shops/images.png",
        title: "Mapple Earphones",
        type: "180",
        universite : "Université De Tunis EL Manar",
        auteur: "alex rtfqt",
        prixLecture: 1.900,
        prixTelechargement: 2.800,
      },
    
    ],
  }
  export default Sdata